
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/notes?serverTimezone=${user.timezone}
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: Aldana123456.
    jpa:
        hibernate:
            ddl-auto: update

    main:
        web-application-type: none

logging:
    level:
        root : info

